# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: required
dist: focal
cache:
  - packages
warnings_are_errors: false
r:
  - oldrel

before_install:
  - sudo apt-get -y install libharfbuzz-dev libfribidi-dev

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - devscripts # checkbashisms
      - libgdal-dev
      - libproj-dev
      - libgeos-dev
      - libudunits2-dev
      - libnetcdf-dev
      - netcdf-bin

# set NOT_CRAN to true to ensure that skip_on_cran tests are run here
env:
  - NOT_CRAN=true

after_success:
- Rscript -e 'covr::codecov()'